"""Changed location to city for API implementation

Revision ID: 3b758e498afb
Revises: 6096d4b57956
Create Date: 2024-11-21 17:34:53.747758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b758e498afb'
down_revision = '6096d4b57956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('city')

    # ### end Alembic commands ###
